"use client";

import { useEffect, useState } from "react";

type CycleState = { cycleId:string; runId:string; cycleNumber:number; maxCycles:number; status:string; lastAction:string; lastReason:string; workerTaskId?:string; workerStatus?:string; attempts:number; updatedAt:string };
type PipelineStage = { id:string; label:string; state:"done"|"active"|"blocked"|"pending"; detail:string };
type WorkerPayload = { success?: boolean; runtime?: { enabled?: boolean; maxConcurrency?: number; defaultTimeoutMs?: number; defaultMaxAttempts?: number }; records?: Array<{ taskId:string; runId:string; status:string; attempt:number; maxAttempts:number; provider:string; changedFiles:string[]; error?:string; task?:{title?:string;targetPaths?:string[];implementationIntent?:string|null;implementationIntentSource?:string|null;researchContext?:{strategyId?:string|null;symbol?:string|null;timeframe?:string|null;researchRunId?:string|null;researchDecision?:string|null}} }>; cycles?: CycleState[]; selectedCycle?: CycleState | null; safety?: Record<string, boolean>; latestFeedback?: { kind?:string; recommendation?:string; summary?:string; researchImpact?:string; learningEligible?:boolean; evidenceQuality?:string; validationFailures?:number; validationPasses?:number; nextCycleInput?: Record<string, unknown> } | null; events?: Array<{from:string|null;to:string;at:string;message?:string}>; evidence?: Array<{status:string;success:boolean;changedFiles:string[];summary?:string}> };

const statusClass: Record<string,string> = { ACCEPTED:"bg-emerald-100 text-emerald-700", FAILED:"bg-red-100 text-red-700", BUDGET_EXCEEDED:"bg-red-100 text-red-700", REVIEW_REQUIRED:"bg-amber-100 text-amber-700", DISPATCHED:"bg-blue-100 text-blue-700", CONTINUE_RESEARCH:"bg-sky-100 text-sky-700", RUNNING:"bg-muted text-muted-foreground" };
const stageClass: Record<PipelineStage["state"],string> = { done:"border-emerald-200 bg-emerald-50", active:"border-blue-200 bg-blue-50", blocked:"border-amber-200 bg-amber-50", pending:"border-border bg-card" };

function safetyEntries(safety: Record<string, boolean> | undefined) { return [["Research only",safety?.researchOnly],["Execution enabled",safety?.executionEnabled],["DB writes",safety?.databaseWriteEnabled],["Broker execution",safety?.brokerExecutionEnabled],["Main repo mutation",safety?.mainRepoMutation],["Automatic PR",safety?.automaticPr],["Automatic merge",safety?.automaticMerge]] as const; }

function buildPipeline(current: NonNullable<WorkerPayload["records"]>[number] | null, cycle: CycleState | null, feedback: WorkerPayload["latestFeedback"]): PipelineStage[] {
  const hasResearch = Boolean(current?.task?.researchContext?.strategyId || current?.task?.researchContext?.researchRunId || current?.task?.researchContext?.researchDecision);
  const status = current?.status ?? cycle?.workerStatus ?? "";
  const accepted = status === "ACCEPTED" || feedback?.kind === "IMPLEMENTATION_VERIFIED";
  const failed = status === "FAILED" || status === "REVIEW_REQUIRED" || feedback?.kind === "IMPLEMENTATION_BLOCKED" || feedback?.kind === "IMPLEMENTATION_REVIEW";
  const dispatched = Boolean(current || cycle?.workerTaskId);
  return [
    { id:"research", label:"Research", state:hasResearch?"done":"pending", detail: hasResearch ? [current?.task?.researchContext?.strategyId,current?.task?.researchContext?.symbol,current?.task?.researchContext?.timeframe].filter(Boolean).join(" · ") || "Research context linked" : "Research context not attached to this worker" },
    { id:"decision", label:"AI Decision", state:current?.task?.researchContext?.researchDecision?"done":cycle?.lastAction?"done":"pending", detail:current?.task?.researchContext?.researchDecision ?? cycle?.lastAction ?? "Waiting for research decision" },
    { id:"task", label:"Implementation Task", state:dispatched?"done":"pending", detail:current?.task?.title ?? cycle?.workerTaskId ?? "No worker task" },
    { id:"worker", label:"Worker / Cursor", state:accepted||failed?"done":dispatched?"active":"pending", detail:current ? `${current.provider} · ${status}` : "Not dispatched" },
    { id:"validation", label:"Validation", state:accepted?"done":failed?"blocked":current?.status === "VALIDATING"?"active":"pending", detail:accepted?"Validation accepted":failed?"Validation/evidence requires review":"Waiting for validation" },
    { id:"evidence", label:"Evidence", state:feedback?"done":current?.status === "ACCEPTED"?"done":failed?"blocked":"pending", detail:feedback?.evidenceQuality ? `Quality ${feedback.evidenceQuality}` : "No feedback evidence yet" },
    { id:"feedback", label:"Feedback", state:feedback?"done":"pending", detail:feedback?.summary ?? "Waiting for worker feedback" },
    { id:"next", label:"Next Cycle", state:feedback?.nextCycleInput && feedback.kind !== "IMPLEMENTATION_VERIFIED" ? "active" : feedback ? "done" : "pending", detail:feedback ? (feedback.nextCycleInput?.nextCycleAllowed === false ? "Cycle handoff closed" : "Cycle handoff available") : "No handoff yet" },
  ];
}

export function WorkerCockpit() {
  const [data,setData]=useState<WorkerPayload|null>(null); const [selected,setSelected]=useState<string|null>(null); const [selectedCycleId,setSelectedCycleId]=useState<string|null>(null); const [loading,setLoading]=useState(false);
  async function load(taskId?:string,cycleId?:string){setLoading(true);try{const params=new URLSearchParams();if(taskId)params.set("taskId",taskId);else params.set("limit","25");if(cycleId)params.set("cycleId",cycleId);const response=await fetch(`/api/workers?${params.toString()}`,{cache:"no-store"});setData(await response.json());}finally{setLoading(false);}}
  useEffect(()=>{void load(selected??undefined,selectedCycleId??undefined);const timer=window.setInterval(()=>void load(selected??undefined,selectedCycleId??undefined),5000);return()=>window.clearInterval(timer);},[selected,selectedCycleId]);
  const records=data?.records??[], cycles=data?.cycles??[], current=selected?records.find(r=>r.taskId===selected) ?? null:null, currentCycle=data?.selectedCycle??(selectedCycleId?cycles.find(c=>c.cycleId===selectedCycleId) ?? null:null), currentEvents=data?.events??[], currentEvidence=data?.evidence??[], currentFeedback=data?.latestFeedback??null, pipeline=buildPipeline(current,currentCycle,currentFeedback);
  function selectCycle(cycle:CycleState){setSelectedCycleId(cycle.cycleId);if(cycle.workerTaskId)setSelected(cycle.workerTaskId);void load(cycle.workerTaskId,cycle.cycleId);}
  return <section className="rounded-2xl border border-border bg-card p-6 shadow-sm space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted-foreground">Autonomous implementation layer</p><h2 className="text-2xl font-bold">Worker Cockpit</h2><p className="mt-1 text-xs text-muted-foreground">Research → Decision → Task → Worker → Validation → Evidence → Feedback → Next Cycle</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${data?.runtime?.enabled?"bg-emerald-100 text-emerald-700":"bg-muted text-muted-foreground"}`}>{data?.runtime?.enabled?"ENABLED":"DISABLED"}</span><button onClick={()=>void load(selected??undefined,selectedCycleId??undefined)} disabled={loading} className="rounded-xl border border-border px-3 py-2 text-sm">{loading?"...":"Refresh"}</button></div></div>

    <div className="grid gap-3 md:grid-cols-5">{["QUEUED","RUNNING","ACCEPTED","REVIEW_REQUIRED","FAILED"].map(status=><div key={status} className="rounded-xl border border-border p-3"><div className="text-xs text-muted-foreground">{status}</div><div className="mt-1 text-xl font-bold">{records.filter(r=>r.status===status).length}</div></div>)}</div>

    <div className="rounded-2xl border border-border p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Operations flow</p><h3 className="font-semibold">Research-to-Worker Pipeline</h3></div>{current && <span className="text-xs text-muted-foreground">{current.task?.researchContext?.symbol ?? "Research context"}</span>}</div><div className="grid gap-2 md:grid-cols-4 xl:grid-cols-8">{pipeline.map((stage,index)=><div key={stage.id} className={`rounded-xl border p-3 ${stageClass[stage.state]}`}><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-bold uppercase tracking-wide">{index+1}. {stage.label}</span><span className="text-[10px] font-semibold uppercase">{stage.state}</span></div><p className="mt-2 line-clamp-3 text-xs text-muted-foreground">{stage.detail}</p></div>)}</div></div>

    <div className="rounded-2xl border border-border p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Persistent runtime history</p><h3 className="font-semibold">Autonomous Cycle Timeline</h3></div><span className="text-xs text-muted-foreground">{cycles.length} cycles</span></div>{cycles.length===0?<p className="text-sm text-muted-foreground">Henüz cycle geçmişi yok.</p>:<div className="space-y-3">{cycles.map(cycle=><button type="button" key={cycle.cycleId} onClick={()=>selectCycle(cycle)} className={`flex w-full gap-3 rounded-xl border p-3 text-left transition ${selectedCycleId===cycle.cycleId?"border-foreground bg-muted/60":"border-border hover:bg-muted"}`}><div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-xs font-bold">{cycle.cycleNumber}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-medium">{cycle.lastAction}</div><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${statusClass[cycle.status]??"bg-muted text-muted-foreground"}`}>{cycle.status}</span></div><div className="mt-1 text-xs text-muted-foreground">{cycle.lastReason} · attempt {cycle.attempts} · budget {cycle.cycleNumber}/{cycle.maxCycles}</div><div className="mt-1 truncate text-[11px] text-muted-foreground">{cycle.workerTaskId?`worker ${cycle.workerTaskId} · `:""}{cycle.cycleId} · {new Date(cycle.updatedAt).toLocaleString()}</div></div></button>)}</div>}</div>

    <div className="grid gap-4 lg:grid-cols-[1.15fr_1fr]"><div className="space-y-2">{records.length===0?<p className="text-sm text-muted-foreground">Henüz Worker kaydı yok.</p>:records.map(record=><button type="button" key={record.taskId} onClick={()=>{setSelected(record.taskId);setSelectedCycleId(null);void load(record.taskId)}} className={`w-full rounded-xl border p-4 text-left transition ${selected===record.taskId?"border-foreground bg-muted/60":"border-border hover:bg-muted"}`}><div className="flex justify-between gap-3"><strong>{record.task?.title??record.taskId}</strong><span className="text-xs font-semibold">{record.status}</span></div><div className="mt-1 text-xs text-muted-foreground">{record.provider} · attempt {record.attempt}/{record.maxAttempts}</div><div className="mt-1 text-xs text-muted-foreground">Intent: {record.task?.implementationIntent??"NONE"}</div>{record.task?.researchContext?.strategyId&&<div className="mt-1 text-[11px] text-muted-foreground">Strategy {record.task.researchContext.strategyId} · {record.task.researchContext.symbol??"—"} · {record.task.researchContext.timeframe??"—"}</div>}</button>)}</div>
      <div className="space-y-4"><div className="rounded-xl border border-border p-4"><h3 className="font-semibold">Safety Guardrails</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{safetyEntries(data?.safety).map(([label,value])=><div key={label} className="flex items-center justify-between rounded-lg border border-border px-3 py-2 text-xs"><span>{label}</span><span className={`rounded-full px-2 py-1 font-semibold ${value?"bg-emerald-100 text-emerald-700":"bg-muted text-muted-foreground"}`}>{value?"ON":"OFF"}</span></div>)}</div></div>
        {current&&<div className="rounded-xl border border-border p-4 space-y-3"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">Research Context</h3><span className="rounded-full bg-muted px-2 py-1 text-[11px]">RESEARCH_ONLY</span></div><div className="grid gap-2 text-xs sm:grid-cols-2"><div><span className="text-muted-foreground">Strategy</span><div className="font-medium">{current.task?.researchContext?.strategyId??"—"}</div></div><div><span className="text-muted-foreground">Symbol</span><div className="font-medium">{current.task?.researchContext?.symbol??"—"}</div></div><div><span className="text-muted-foreground">Timeframe</span><div className="font-medium">{current.task?.researchContext?.timeframe??"—"}</div></div><div><span className="text-muted-foreground">Research Run</span><div className="truncate font-medium">{current.task?.researchContext?.researchRunId??"—"}</div></div><div className="sm:col-span-2"><span className="text-muted-foreground">Decision</span><div className="mt-1 rounded-lg border border-border bg-muted/40 p-2 font-medium">{current.task?.researchContext?.researchDecision??"No decision metadata attached"}</div></div></div></div>}
        {currentCycle&&<div className="rounded-xl border border-border p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">Selected Cycle</h3><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${statusClass[currentCycle.status]??"bg-muted text-muted-foreground"}`}>{currentCycle.status}</span></div><div className="mt-2 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2"><div>Cycle: {currentCycle.cycleNumber}/{currentCycle.maxCycles}</div><div>Attempt: {currentCycle.attempts}</div><div>Action: {currentCycle.lastAction}</div><div>Worker: {currentCycle.workerTaskId??"—"}</div><div className="sm:col-span-2">Reason: {currentCycle.lastReason}</div></div></div>}
        {current&&<div className="rounded-xl border border-border p-4 space-y-2"><h3 className="font-semibold">Selected Worker</h3><div className="text-sm">{current.task?.title??current.taskId}</div><div className="text-xs text-muted-foreground">Targets: {(current.task?.targetPaths??[]).join(", ")||"—"}</div><div className="text-xs text-muted-foreground">Changed: {current.changedFiles.join(", ")||"—"}</div>{current.error&&<div className="rounded-lg bg-red-50 p-3 text-xs text-red-700">{current.error}</div>}</div>}
      </div></div>

    {(selected||selectedCycleId)&&<div className="grid gap-4 lg:grid-cols-3"><div className="rounded-xl border border-border p-4"><h3 className="font-semibold">Lifecycle Events</h3>{currentEvents.length===0?<p className="mt-2 text-xs text-muted-foreground">Event kaydı yok.</p>:<div className="mt-3 space-y-2">{currentEvents.slice(-8).reverse().map((event,index)=><div key={`${event.at}-${index}`} className="rounded-lg border border-border p-2 text-xs"><div className="font-medium">{event.from??"—"} → {event.to}</div><div className="mt-1 text-muted-foreground">{event.message??"Worker state transition"}</div><div className="mt-1 text-[11px] text-muted-foreground">{new Date(event.at).toLocaleString()}</div></div>)}</div>}</div><div className="rounded-xl border border-border p-4"><h3 className="font-semibold">Validation Evidence</h3>{currentEvidence.length===0?<p className="mt-2 text-xs text-muted-foreground">Evidence kaydı yok.</p>:<div className="mt-3 space-y-2">{currentEvidence.slice(-6).reverse().map((item,index)=><div key={`${item.status}-${index}`} className="rounded-lg border border-border p-2 text-xs"><div className="flex justify-between gap-2"><span className="font-medium">{item.status}</span><span className={item.success?"text-emerald-700":"text-red-700"}>{item.success?"PASS":"FAIL"}</span></div><div className="mt-1 text-muted-foreground">Changed: {item.changedFiles.join(", ")||"—"}</div>{item.summary&&<div className="mt-1 text-muted-foreground">{item.summary}</div>}</div>)}</div>}</div><div className="rounded-xl border border-border p-4"><h3 className="font-semibold">Latest Feedback</h3>{currentFeedback?<div className="mt-3 space-y-2 text-xs"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-muted px-2 py-1 font-semibold">{currentFeedback.kind??"UNKNOWN"}</span>{currentFeedback.recommendation&&<span className="rounded-full bg-muted px-2 py-1">{currentFeedback.recommendation}</span>}</div><p className="text-muted-foreground">{currentFeedback.summary??"—"}</p><div className="grid grid-cols-2 gap-2 text-muted-foreground"><div>Evidence: {currentFeedback.evidenceQuality??"—"}</div><div>Impact: {currentFeedback.researchImpact??"—"}</div><div>Validation pass: {currentFeedback.validationPasses??0}</div><div>Validation fail: {currentFeedback.validationFailures??0}</div><div>Learning: {currentFeedback.learningEligible?"eligible":"blocked"}</div></div></div>:<p className="mt-2 text-xs text-muted-foreground">Feedback kaydı yok.</p>}</div></div>}
  </section>;
}
