import crypto from "node:crypto";
import type { AgentContext } from "@/components/agents/agent-types";
import type { WorkerProviderId, WorkerTask } from "./worker-types";
type R=Record<string,unknown>;
const rec=(v:unknown):R=>v&&typeof v==="object"&&!Array.isArray(v)?v as R:{};
const text=(v:unknown,f="")=>typeof v==="string"&&v.trim()?v.trim():f;
const output=(c:AgentContext,id:string)=>rec(c.previousResults?.[id as keyof typeof c.previousResults]?.output);
const nested=(s:R,...keys:string[]):unknown=>{let c:unknown=s;for(const k of keys)c=rec(c)[k];return c;};
const decisionLabel=(decision:R)=>{for(const key of ["action","decision","recommendation","status","reason"]){const value=decision[key];if(typeof value==="string"&&value.trim())return value.trim();}return null;};
const provider=(value:unknown):WorkerProviderId=>value==="cursor"||value==="hermes"?value:"hermes";
const clampTimeoutMs=(v:unknown):number=>{const n=typeof v==="number"&&Number.isFinite(v)?v:Number(process.env.MARKETHQ_WORKER_TIMEOUT_MS??120000)||120000;return Math.min(900000,Math.max(60000,Math.round(n)));};
export function buildWorkerTaskFromResearchDecision(input:{runId:string;strategyId?:string;symbol?:string;timeframe?:string;decision?:unknown;queueTask?:unknown;instructions?:string;targetPaths?:string[];validationCommand?:string;implementationIntent?:string;provider?:WorkerProviderId;timeoutMs?:number}):WorkerTask{const d=rec(input.decision),q=rec(input.queueTask);const question=text(d.nextResearchQuestion??nested(d,"researchLoop","nextResearchQuestion")??d.researchQuestion??q.question,"MarketHQ research worker task");const targets=(input.targetPaths??[]).map(p=>p.replaceAll("\\","/").replace(/^\.\//,""));if(!targets.length)throw new Error("Worker Task Builder requires explicit targetPaths; it will never infer a broad repository target from a research question.");const selectedProvider=provider(input.provider??process.env.MARKETHQ_DEFAULT_WORKER_PROVIDER);const seed=[input.strategyId??"",input.symbol??"",input.timeframe??"1d",question,input.implementationIntent??"NONE",selectedProvider,...targets].join("|");const digest=crypto.createHash("sha256").update(seed).digest("hex").slice(0,20);const decisionSummary=decisionLabel(d);return{taskId:`mhq-worker-task-${digest}`,runId:input.runId,title:`Research implementation: ${question.slice(0,120)}`,instructions:text(input.instructions,`Implement the requested research task safely. Research question: ${question}`),targetPaths:targets,provider:selectedProvider,validationCommand:input.validationCommand,timeoutMs:clampTimeoutMs(input.timeoutMs),attempt:1,maxAttempts:2,metadata:{source:"MARKETHQ_RESEARCH_DECISION",strategyId:input.strategyId??null,symbol:input.symbol??null,timeframe:input.timeframe??"1d",researchRunId:input.runId,researchQuestion:question,researchDecision:decisionSummary,implementationIntent:input.implementationIntent??null,implementationIntentSource:input.implementationIntent?"EXPLICIT_IMPLEMENTATION_INTENT":"NONE",logicalTaskKey:`research|${input.strategyId??""}|${input.symbol??""}|${input.timeframe??"1d"}|${digest}`,mutationAuthorized:false,automaticMerge:false,automaticPr:false}};}
export function buildWorkerTaskFromAgentContext(input:{context:AgentContext;targetPaths:string[];instructions?:string;validationCommand?:string;implementationIntent?:string;provider?:WorkerProviderId}):WorkerTask{const decision=output(input.context,"research-decision"),queue=output(input.context,"research-queue"),selected=rec(nested(queue,"queue","selectedTask")),strategy=output(input.context,"strategy");return buildWorkerTaskFromResearchDecision({runId:input.context.runId,strategyId:text(input.context.strategyId??strategy.strategyId),symbol:text(input.context.symbol??selected.symbol),timeframe:text(input.context.timeframe??selected.timeframe,"1d"),decision,queueTask:selected,instructions:input.instructions,targetPaths:input.targetPaths,validationCommand:input.validationCommand,implementationIntent:input.implementationIntent??(typeof input.context.metadata?.implementationIntent==="string"?input.context.metadata.implementationIntent:undefined),provider:input.provider});}
