# -*- coding: utf-8 -*-
"""Phase G — Research Validation & Historical Setup Intelligence.

Models for historical validation of Research-Backed Setups.

Flow:
  Historical OHLCV
      ↓
  FeatureSnapshot @ cutoff
      ↓
  Research Agents → Opportunity → Setup
      ↓
  Historical Replay (Phase G)
      ↓
  Outcome
      ↓
  Validation
      ↓
  Claims

Research-only. No trading, no broker, no live execution.
"""

from __future__ import annotations

import math
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


# =========================================================
# ENUM
# =========================================================

class DataSufficiency(str, Enum):
    DATA_SUFFICIENT = "DATA_SUFFICIENT"
    LIMITED = "LIMITED"
    LOW_SAMPLE = "LOW_SAMPLE"
    UNAVAILABLE = "UNAVAILABLE"


class OutcomeType(str, Enum):
    TARGET_1_REACHED = "TARGET_1_REACHED"
    TARGET_2_REACHED = "TARGET_2_REACHED"
    TARGET_3_REACHED = "TARGET_3_REACHED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"
    NO_ENTRY = "NO_ENTRY"
    AMBIGUOUS = "AMBIGUOUS"
    INCOMPLETE_DATA = "INCOMPLETE_DATA"


class ClaimStatus(str, Enum):
    TESTED = "TESTED"
    SUPPORTED = "SUPPORTED"
    UNSTABLE = "UNSTABLE"
    REJECTED = "REJECTED"
    UNTESTED = "UNTESTED"


# =========================================================
# HISTORICAL OUTCOME
# =========================================================

@dataclass
class HistoricalOutcome:
    """Historical outcome of a setup replay.

    Generated by replaying a ResearchBackedSetup against
    historical OHLCV data after the cutoff time.
    """
    outcome_id: str = ""
    setup_id: str = ""
    opportunity_id: str = ""
    symbol: str = ""
    timeframe: str = ""
    cutoff_time: str = ""
    direction: str = "UNKNOWN"
    regime: str = "UNKNOWN"
    setup_type: str = ""
    strategy_family: str = ""

    # Setup geometry (from setup)
    entry_zone_low: float | None = None
    entry_zone_high: float | None = None
    entry_reference: float | None = None
    invalidation_price: float | None = None
    target_1: float | None = None
    target_2: float | None = None
    target_3: float | None = None

    # Outcome
    entry_triggered: bool = False
    entry_time: str = ""
    invalidation_hit: bool = False
    invalidation_time: str = ""
    t1_hit: bool = False
    t1_time: str = ""
    t2_hit: bool = False
    t2_time: str = ""
    t3_hit: bool = False
    t3_time: str = ""

    # Metrics
    bars_to_entry: int = -1
    bars_to_invalidation: int = -1
    bars_to_t1: int = -1
    bars_to_t2: int = -1
    bars_to_t3: int = -1
    max_favorable_excursion: float = 0.0
    max_adverse_excursion: float = 0.0
    realized_r: float = 0.0
    exit_reason: str = ""  # INVALIDATION / TARGET_1 / TARGET_2 / TARGET_3 / EXPIRY / NO_ENTRY / AMBIGUOUS

    # Status
    outcome_type: str = OutcomeType.INCOMPLETE_DATA
    ambiguous: bool = False
    no_entry: bool = False

    # Quality reference
    quality_score: float | None = None
    confidence: float = 0.0
    uncertainty: float = 1.0
    data_availability: float = 0.0

    # Traceability
    feature_snapshot_id: str = ""
    source_agents: list[dict[str, Any]] = field(default_factory=list)
    evidence_traces: list[dict[str, Any]] = field(default_factory=list)

    created_at: str = ""

    def __post_init__(self) -> None:
        now = datetime.now(timezone.utc).isoformat()
        if not self.outcome_id:
            self.outcome_id = f"OUT-{uuid.uuid4().hex[:10].upper()}"
        if not self.created_at:
            self.created_at = now

    def to_dict(self) -> dict[str, Any]:
        return {
            "outcome_id": self.outcome_id,
            "setup_id": self.setup_id,
            "opportunity_id": self.opportunity_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "cutoff_time": self.cutoff_time,
            "direction": self.direction,
            "regime": self.regime,
            "setup_type": self.setup_type,
            "strategy_family": self.strategy_family,
            "entry_zone_low": self.entry_zone_low,
            "entry_zone_high": self.entry_zone_high,
            "entry_reference": self.entry_reference,
            "invalidation_price": self.invalidation_price,
            "target_1": self.target_1,
            "target_2": self.target_2,
            "target_3": self.target_3,
            "entry_triggered": self.entry_triggered,
            "entry_time": self.entry_time,
            "invalidation_hit": self.invalidation_hit,
            "invalidation_time": self.invalidation_time,
            "t1_hit": self.t1_hit,
            "t1_time": self.t1_time,
            "t2_hit": self.t2_hit,
            "t2_time": self.t2_time,
            "t3_hit": self.t3_hit,
            "t3_time": self.t3_time,
            "bars_to_entry": self.bars_to_entry,
            "bars_to_invalidation": self.bars_to_invalidation,
            "bars_to_t1": self.bars_to_t1,
            "bars_to_t2": self.bars_to_t2,
            "bars_to_t3": self.bars_to_t3,
            "max_favorable_excursion": self.max_favorable_excursion,
            "max_adverse_excursion": self.max_adverse_excursion,
            "realized_r": self.realized_r,
            "exit_reason": self.exit_reason,
            "outcome_type": self.outcome_type,
            "ambiguous": self.ambiguous,
            "no_entry": self.no_entry,
            "quality_score": self.quality_score,
            "confidence": self.confidence,
            "uncertainty": self.uncertainty,
            "data_availability": self.data_availability,
            "feature_snapshot_id": self.feature_snapshot_id,
            "source_agents": self.source_agents,
            "evidence_traces": self.evidence_traces,
            "created_at": self.created_at,
        }


# =========================================================
# VALIDATION METRICS
# =========================================================

@dataclass
class ValidationMetrics:
    """Validation metrics for a set of historical outcomes."""
    n_setups: int = 0
    n_entries: int = 0
    n_invalidations: int = 0
    n_expired: int = 0
    n_no_entry: int = 0
    n_ambiguous: int = 0

    t1_hit_rate: float = 0.0
    t2_hit_rate: float = 0.0
    t3_hit_rate: float = 0.0
    invalidation_rate: float = 0.0
    entry_rate: float = 0.0

    avg_r: float = 0.0
    median_r: float = 0.0
    std_r: float = 0.0
    min_r: float = 0.0
    max_r: float = 0.0

    avg_mfe: float = 0.0
    avg_mae: float = 0.0

    avg_bars_to_entry: float = 0.0
    avg_bars_to_invalidation: float = 0.0
    avg_bars_to_t1: float = 0.0

    data_sufficiency: str = DataSufficiency.UNAVAILABLE.value
    lookahead_status: str = "NOT_AUDITED"

    def to_dict(self) -> dict[str, Any]:
        return {
            "n_setups": self.n_setups,
            "n_entries": self.n_entries,
            "n_invalidations": self.n_invalidations,
            "n_expired": self.n_expired,
            "n_no_entry": self.n_no_entry,
            "n_ambiguous": self.n_ambiguous,
            "t1_hit_rate": self.t1_hit_rate,
            "t2_hit_rate": self.t2_hit_rate,
            "t3_hit_rate": self.t3_hit_rate,
            "invalidation_rate": self.invalidation_rate,
            "entry_rate": self.entry_rate,
            "avg_r": self.avg_r,
            "median_r": self.median_r,
            "std_r": self.std_r,
            "min_r": self.min_r,
            "max_r": self.max_r,
            "avg_mfe": self.avg_mfe,
            "avg_mae": self.avg_mae,
            "avg_bars_to_entry": self.avg_bars_to_entry,
            "avg_bars_to_invalidation": self.avg_bars_to_invalidation,
            "avg_bars_to_t1": self.avg_bars_to_t1,
            "data_sufficiency": self.data_sufficiency,
            "lookahead_status": self.lookahead_status,
        }


# =========================================================
# RESEARCH CLAIM
# =========================================================

@dataclass
class ResearchClaim:
    """A research claim with validation status."""
    claim_id: str = ""
    claim_text: str = ""
    claim_type: str = ""  # hypothesis / finding / observation
    status: str = ClaimStatus.UNTESTED.value
    evidence: list[dict[str, Any]] = field(default_factory=list)
    sample_size: int = 0
    validation_window: str = ""
    temporal_stability: str = "NOT_TESTED"
    confidence: float = 0.0
    uncertainty: float = 1.0
    created_at: str = ""
    updated_at: str = ""

    def __post_init__(self) -> None:
        now = datetime.now(timezone.utc).isoformat()
        if not self.claim_id:
            self.claim_id = f"CLAIM-{uuid.uuid4().hex[:8].upper()}"
        if not self.created_at:
            self.created_at = now
        if not self.updated_at:
            self.updated_at = now

    def to_dict(self) -> dict[str, Any]:
        return {
            "claim_id": self.claim_id,
            "claim_text": self.claim_text,
            "claim_type": self.claim_type,
            "status": self.status,
            "evidence": self.evidence,
            "sample_size": self.sample_size,
            "validation_window": self.validation_window,
            "temporal_stability": self.temporal_stability,
            "confidence": self.confidence,
            "uncertainty": self.uncertainty,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }